# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

# whitelist
branches:
  only:
    - master
    - develop
    - unifySelection

language: r
sudo: required
dist: trusty
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - netcdf-bin
      - libnetcdf-dev

r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
