# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
sudo: required
dist: trusty
warnings_are_errors: true

addons:
  apt:
    packages:
      - libhdf5-7
      - libhdf5-dev
      - libhdf5-serial-dev
      - libgdal-dev
      - libproj-dev
#r_github_packages:
#  - jimhester/covr
#after_success:
#  - Rscript -e 'covr::codecov()'
